recipe: &recipe
  working_directory: ~/dmd
  docker:
    - image: circleci/buildpack-deps:18.04
  steps:
    - run:
        command: sudo apt-get update --quiet=2 && sudo apt-get install gdb tzdata --assume-yes --quiet=2
        name: Install dependencies
    - checkout
    - run:
        command: git clone https://github.com/dlang/phobos ../phobos --depth 1
        name: Checkout Phobos
    - run:
        command: git clone https://github.com/dlang/druntime ../druntime --depth 1
        name: Checkout DRuntime
    - restore_cache:
        keys:
          - v0-build-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          - v0-build-{{ arch }}-{{ .Branch }}-
          - v0-build-{{ arch }}-
    - run:
        command: make -j$N -f posix.mak BUILD=$BUILD AUTO_BOOTSTRAP=1
        name: Build DMD
    - run:
        command: make -j$N -C ../druntime -f posix.mak BUILD=$BUILD
        name: Build DRuntime
    - run:
        command: make -j$N -C ../phobos -f posix.mak BUILD=$BUILD
        name: Build Phobos
    - save_cache:
        key: v0-build-{{ arch }}-{{ .Branch }}-{{ .Revision }}
        paths:
          - generated
          - ../phobos/generated
          - ../druntime/generated
    - run:
        command: rm -rf test/compilable/issue17167.sh
        name: Temporarily the failing long file name test has been removed
    - run:
        command: make -j$N -f posix.mak BUILD=$BUILD AUTO_BOOTSTRAP=1 test
        name: Test DMD
    - run:
        command: make -j$N -C ../druntime -f posix.mak BUILD=$BUILD unittest
        name: Test DRuntime
    - run:
        command: make -j2 -C ../phobos -f posix.mak BUILD=$BUILD AUTO_BOOTSTRAP=1 unittest
        name: Test Phobos

version: 2
jobs:
  release:
    <<: *recipe
    environment:
      - BUILD: release
      - MODEL: 64
      - N: 4
  # debug:
  #   <<: *recipe
  #   environment:
  #     - BUILD: debug
  #     - MODEL: 64
  #     - N: 4

workflows:
  version: 2
  all:
    jobs:
      - release
      # - debug
