recipe: &recipe
  working_directory: ~/dmd
  docker:
    - image: circleci/buildpack-deps:18.04
  steps:
    - checkout
    - run:
        command: ./.circleci/run.sh install-deps
        name: Install dependencies
    - run:
        # needs to be a separate step, s.t. `run.sh` gets updated too
        command: ./.circleci/run.sh setup-repos
        name: Merge with upstream + clone DRuntime & Phobos
    # - run:
    #     command: ./.circleci/run.sh all
    #     name: Run all
    - run:
        command: make -j$N -f posix.mak BUILD=$BUILD AUTO_BOOTSTRAP=1
        name: Build DMD
    - run:
        command: make -j$N -C ../druntime -f posix.mak BUILD=$BUILD
        name: Build DRuntime
    - run:
        command: make -j$N -C ../phobos -f posix.mak BUILD=$BUILD
        name: Build Phobos
    - run:
        command: false
        name: Stop!
    # - run:
    #     command: make -j$N -f posix.mak BUILD=$BUILD AUTO_BOOTSTRAP=1 test
    #     name: Test DMD
    # - run:
    #     command: make -j$N -C ../druntime -f posix.mak BUILD=$BUILD unittest
    #     name: Test DRuntime
    # - run:
    #     command: make -j$N -C ../phobos -f posix.mak BUILD=$BUILD AUTO_BOOTSTRAP=1 unittest
    #     name: Test Phobos

version: 2
jobs:
  release:
    <<: *recipe
    environment:
      - BUILD: release
      - MODEL: 64
      - N: 4
  debug:
    <<: *recipe
    environment:
      - BUILD: debug
      - MODEL: 64
      - N: 4

workflows:
  version: 2
  all:
    jobs:
      - release
      # - debug
