version: 2
jobs:
  build:
    working_directory: ~/dmd
    docker:
      - image: circleci/buildpack-deps:18.04
    parallelism: 1
    steps:
      - checkout
      - run:
          command: ./.circleci/run.sh install-deps
          name: Install dependencies
      - run:
          command: false
          name: halt
workflows:
  version: 2
  all:
    jobs:
      - build
